import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../layout/Header";
import Footer from "../layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header />
        <div className={"max-w-[1024px] m-auto min-h-[70vh]"}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
